# Generated by Django 5.0.2 on 2025-03-30 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='academic_status',
            field=models.CharField(blank=True, choices=[('attending', '재학'), ('leave', '휴학'), ('graduated', '졸업'), ('expected_graduation', '졸업예정')], max_length=20, null=True, verbose_name='학적상태'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년')], null=True, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='전공'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(blank=True, help_text='"-" 없이 숫자만 입력해주세요.', max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', '올바른 전화번호를 입력해주세요.')], verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='university',
            field=models.CharField(blank=True, max_length=100, verbose_name='대학교'),
        ),
    ]
