# Generated by Django 5.0.2 on 2025-03-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicant_academic_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='preferred_interview_times',
        ),
        migrations.AddField(
            model_name='application',
            name='interview_sat_afternoon',
            field=models.BooleanField(default=False, verbose_name='토요일 오후'),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_sat_morning',
            field=models.BooleanField(default=False, verbose_name='토요일 오전'),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_sun_afternoon',
            field=models.BooleanField(default=False, verbose_name='일요일 오후'),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_sun_morning',
            field=models.BooleanField(default=False, verbose_name='일요일 오전'),
        ),
    ]
