# Generated by Django 5.0.2 on 2025-03-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='photo',
        ),
        migrations.AddField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, help_text='3x4cm 사진을 업로드해주세요.', null=True, upload_to='applicant_photos/%Y/%m/', verbose_name='프로필 사진'),
        ),
    ]
